{% set name = "transonic" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: df34997a57c0e7d0dd72821f115dc56c3ae06c75616e162829727324de1ebc04

build:
  number: 0
  skip: true  # [py<36]
  entry_points:
    - transonic = transonic.run:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
  run:
    - python
    - astunparse  # [py<39]
    - beniget
    - gast
    - numpy
    - autopep8

test:
  imports:
    - transonic
    - transonic.analyses
    - transonic.backends
    - transonic_cl
  commands:
    - transonic --help

about:
  home: https://foss.heptapod.net/fluiddyn/transonic/
  license: BSD-3-Clause
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Make your Python code fly at transonic speeds!
  description: |
    Transonic is a pure Python package (requiring Python >= 3.6) to easily
    accelerate modern Python-Numpy code with different accelerators (like
    Cython, Pythran, Numba, Cupy, PyTorch, Uarray, etc) opportunistically
    (i.e. if/when they are available).
    The accelerators are not hard dependencies of Transonic; Python codes
    using Transonic run fine without any accelerators installed (of course
    without speedup)!
  doc_url: https://transonic.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
