{% set name = "transonic" %}
{% set version = "0.4.7.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 493b330616135e6bdb6575602694ecff092bbec6402a0b57cc8aedeea2b24c2a

build:
  number: 0
  entry_points:
    - transonic = transonic.run:run
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - astunparse
    - beniget
    - gast
    - numpy
    - autopep8

test:
  imports:
    - transonic
    - transonic.analyses
    - transonic.backends
    - transonic_cl
  commands:
    - transonic --help

about:
  home: https://foss.heptapod.net/fluiddyn/transonic/
  license: BSD-3-Clause
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Make your Python code fly at transonic speeds!
  description: |
    Transonic is a pure Python package (requiring Python >= 3.6) to easily
    accelerate modern Python-Numpy code with different accelerators (like
    Cython, Pythran, Numba, Cupy, PyTorch, Uarray, etc) opportunistically
    (i.e. if/when they are available).
    The accelerators are not hard dependencies of Transonic; Python codes
    using Transonic run fine without any accelerators installed (of course
    without speedup)!
  doc_url: https://transonic.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
