{% set name = "transonic" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c135e256a45797e8e0b83551b1e739cf45b6cc315cd111c0edd7fc4c52fa614

build:
  number: 0
  noarch: python
  entry_points:
    - transonic = transonic.run:run
    - transonic-get-include = transonic_cl.get_includes:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv'

requirements:
  host:
    - python >=3.9
    - pip
    - pdm-backend
  run:
    - python >=3.9
    - beniget ~=0.4.0
    - gast ~=0.5.0
    - numpy
    - autopep8

test:
  imports:
    - transonic
    - transonic.analyses
    - transonic.backends
    - transonic_cl
  commands:
    - transonic --help

about:
  home: https://foss.heptapod.net/fluiddyn/transonic/
  license: BSD-3-Clause
  license_family: OTHER
  license_file: LICENSE.txt
  summary: Make your Python code fly at transonic speeds!
  description: |
    Transonic is a pure Python package (requiring Python >= 3.9) to easily
    accelerate modern Python-Numpy code with different accelerators (like
    Cython, Pythran, Numba, Cupy, PyTorch, Uarray, etc) opportunistically
    (i.e. if/when they are available).
    The accelerators are not hard dependencies of Transonic; Python codes
    using Transonic run fine without any accelerators installed (of course
    without speedup)!
  doc_url: https://transonic.readthedocs.io

extra:
  recipe-maintainers:
    - CyrilleBonamy
    - paugier
    - ashwinvis
