travis:
  secure:
    BINSTAR_TOKEN: Wq2LJ/VMJcq299lFIUqk6MmFrjR/bQKjiCysVskf72lfq4n5kju1BIjCRn8elgAd6qG50zIzYdHT/o2jtLbLhBmRoNMkHCdyCDRtWy+elxCVyR4/vFfwXd5+Hde3Fdty8igVvaGlvbgQPjcc1taLHY4v9vTaClrpwTm8hBCnNJG+n17MwSPm//v4JPJj9vIZrLJs4OlZkE5DbR2m/cT0A8/fOWA1oKHlVzFqvpPiVQx1ZoeO4hBlzXyUlIp/Q2tmOx9S+QVKegEeFO8Fq8EPmEhSnDpBi2UPtaeKGss99qcPdh9+5jOFrj8PNJSfKASu7P67PUFIEjobMYTAqJQck/U24IZfAve/MotYSw5/Tfa+FGizrgxLeKeQ9a0vTIiTZYqBOyM5kLqyqq5TGfi0rAz8e12yqqqIuG+GZvKX2vx7U7Py4ht+0IiOR4cotPZBsJb1qHZLS9P5nOsPsHUDmO2VCPmD/j1H8aDP0kmlcwqPL8RDuTcyy0LhpkNib6NOKdJw9TTjHJYYX1wowFeFjSOChCs9cKgaPTPvf3vbv6jKGcxO8yhKiqtjDOdorody6w2gyX//6Nsn7NM0QbnYAK4PjDFkSz2BCxMD+Jl5WntLEgdaewot1eww+nvBvbpg6zE+5FaXncIqneo02ZTlozATf2zVIN9P2beOGY0Mi9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
