travis:
  secure:
    BINSTAR_TOKEN: JNudyIdvug8t12g/g+TNINoFCVqd4eiXifKx+OEusN76+lV1F96iUMci34uMtxhvAw3IvoAh2b9PMtexhZCCHi2BC7hslMlTd63CXv3varW1PJQ2hS2mV+ZwdR7mv/MBV7zLKKMo0uIYSiGZynBoABYmyni3uixRDQPg2APkMo86ofL+/6Vo7U5jENGmFTrHPbMFYotekONOrRIsWw5Pm00SjYhWaAuFJsRlCygL49eF41W1nYf3BLAHajUKGTFOvMLzb6svquMi5ouB+pC7hMwTSx5MvSBDZLIakZW5nmxc4nJ+wT2dqZVqwBKhbEAnqIECghdNOmOSKZPOEBfDAF9jRm40ojrT5BTDQ0PAWAntZph0I/aI4vwe3iC5x0pxogY/zLZFhfLRzkT4SVKAXab9/AEYIUpupxJflrDNtfdhOgIUd04+LB5vfrOTompuHt+xFAOr/cPZOHDx9WTX7cy348pa+W410gkKULi0OdM3fNc7BLk9qJGh3phxTiA2OcPE1ZLd2veJhVbYsLwg0eXex9SG6pC/YroWqizjMx+rjfgb59R5qYhI8QhAIadu6xjw9b+CUtGV7fXiQt3lvOerHzsRkcSicUacXQkgLmRoJpVyfyBVkW30jK7SaVVaoN0wuml78hKv4EscBP5QcHKDpNvErK+aSO2HYq4cD28=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
